### ISSUE TITLE
Character Generator Skip Adding Bonus Feat

### ISSUE THREAD

**Issue by Helseth** [BunkersAndBadasses/MetaDND#24]
When using the character wizard and selecting fighter, when bonus feat window pops up resume the wizard leaving this window up. Finally select a bonus feat and hit done. Causes null pointer exception.

**Comment by innocentius** [comment]
The null pointer seems fixed. But if the window is leaved out after the character is saved, it could not be closed.

**Comment by innocentius** [comment]
The problem is not fixed. There could still be multiple add feat window pop up.
The best solution should be add a boolean local variable, when everytime the pop up opened make it true, when everytime the pop up close make it false, and when everytime the pop up try to open check if it is false.

**Comment by innocentius** [comment]
Check, fixed.
