### ISSUE TITLE
Clean up "<empty>" strings

### ISSUE THREAD

**Issue by mtkean** [BunkersAndBadasses/MetaDND#28]
I have tried to clean them up where I see them but if you know of any more please clean them up, preferably the " " string. When you write "<empty>" to an xml, when you try to parse it, it looks for the closing "</empty>" because it thinks it is an element

**Comment by mtkean** [comment]
god dammit, see the title

**Comment by innocentius** [comment]
We never save a character using string empty, it is just the to string function that detect the null parameter and display with <empty>. DO NOT change them, they are vital for other elements.

iPhone????

Apr 28, 2015 11:10?"mtkean" <notifications@github.com<mailto:notifications@github.com>> ??????:

god dammit, see the title

##

**Comment by szczerbi** [comment]
Check character.java and wiz9

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
From: innocentius
Date:04/28/2015 12:20 PM (GMT-06:00)
To: BunkersAndBadasses/MetaDND
Subject: Re: [MetaDND] Clean up "" strings (#28)

We never save a character using string empty, it is just the to string function that detect the null parameter and display with <empty>. DO NOT change them, they are vital for other elements.

iPhone????

Apr 28, 2015 11:10?"mtkean" <notifications@github.com<mailto:notifications@github.com>> ??????:

god dammit, see the title

## 

Reply to this email directly or view it on GitHubhttps://github.com/BunkersAndBadasses/MetaDND/issues/28#issuecomment-97122259.

##

**Comment by mtkean** [comment]
To save the character completely I needed to save strings, some of which were populated with <empty>, which threw off the xml.  Let me know which elements need to use them and I can look into trying to fix it, but it looks like it is just being used as an arbitrary string to be checked, so it can be replaced.

**Comment by innocentius** [comment]
Next time this kind of inconsistency, or you feel uncomfortable with something in the code, be sure to get the consent of the coders before you make those change. I'll make this straight: It is unacceptable to change others work before they agree with it. It may cause more inconsistency with other part of application and it is very impolite. 
If I see my part of code change without my permission, I will recognize that as a trouble and I will do a master branch rollback, please check with me first before you want to change any part of it.
