### ISSUE TITLE
Character Wizard: Language deletion bug

### ISSUE THREAD

**Issue by innocentius** [BunkersAndBadasses/MetaDND#29]
Category: Bug
Level: High
Description: Here is a recap:
Known language: add terran and orc
At pick languages: type "Orc" into the text box
Select knownlanguage: terran
click delete,
The orc language will be deleted.
This bug is found in the morning when testing...

**Comment by innocentius** [comment]
Add: Whatever it is in the textbox on the left doesn't matter. The selected is not the last one, the last one will be deleted.

**Comment by Bobperson781** [comment]
This is not a bug, it deletes the last language added.

**Comment by innocentius** [comment]
got it.
