### ISSUE TITLE
Character Sheet: Separate shells

### ISSUE THREAD

**Issue by innocentius** [BunkersAndBadasses/MetaDND#32]
Same as Dungeon map, we don't want the user not able to do anything else with the character sheet open. Consider using another shell when opening up the character sheet.

**Comment by mtkean** [comment]
This how the character sheet was originally set up, but we can't support more than one  character loaded, so making it so it is part of the main shell keeps that. I think the current plan was if they wanted to do something with the character and something else, they would just open up another instance of the app.

**Comment by szczerbi** [comment]
What cant they do? We changed the character sheet specifically to not open in a separate shell..

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
From: innocentius
Date:05/02/2015 10:50 PM (GMT-06:00)
To: BunkersAndBadasses/MetaDND
Subject: [MetaDND] Character Sheet: Separate shells (#32)

Same as Dungeon map, we don't want the user not able to do anything else with the character sheet open. Consider using another shell when opening up the character sheet.

##
